language: objective-c
osx_image: xcode8.2
xcode_workspace: eoscalculator.xcworkspace # path to your xcodeproj folder
xcode_scheme: eoscalculatorTests

script:
- xcodebuild -workspace eoscalculator.xcworkspace -scheme eoscalculatorTests -destination 'platform=iOS Simulator,name=iPhone 6s' test CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
